version: '3'

services: 
    nodkins-nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/home/node/app
        